# environment.yaml

name: ml-cicd
channels:
  - conda-forge
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - flake8=7.0.0
  - pytest=8.2.1
  - requests=2.32.1
  - fastapi=0.63.0
  - uvicorn=0.29.0
  - gunicorn=22.0.0
    