# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        # caching pip dependencies
        cache: 'pip'
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        if [ -f starter/requirements.txt ]; then pip install -r starter/requirements.txt; fi
        # if [ -f starter/requirements.txt ]; then pip install --cache-dir /home/runner/.cache/pip -r starter/requirements.txt ; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 starter --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 starter --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd starter ; pytest -v -p no:warnings  -o log_cli=true  --log-cli-level=INFO
    - name: Deploy
      # The Deploy step executes a curl request to our deploy hook URL only if the Test  with pytest step succeeded.
      # using hook to trigger the deployment only if test succeds, see https://docs.render.com/deploy-hooks for setting the secret
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      
      run: |
        curl "$deploy_url"